### ISSUE TITLE
BUGREPORT - custom bitrate forgets to add a "k" and takes any value 

### ISSUE THREAD

**Issue by seighail3** [cdgriffith/FastFlix#120]
Proof Of Concept 
https://z.zz.ht/fGryL.webm

**Comment by cdgriffith** [comment]
Thanks for the report and example! 

At minimum I need to make it clear that you need to insert the value manually. I wanted it to be customizable so someone could do say 10M instead of 10000k, but I agree I doubt that is the common use case. If anything should make it a drop down option for K / M / G.

**Comment by cdgriffith** [comment]
Changing to only allow integers and making it clear (hopefully) it will be in kbps https://github.com/cdgriffith/FastFlix/releases/tag/4.1.0
