### ISSUE TITLE
The user interface is fucking disgusting

### ISSUE THREAD

**Issue by GitKike98** [cdgriffith/FastFlix#152]
G'day mate. 

Whats wrong with the old one !?

The new one is flat. Ugly - And disgusting 

plus I cant change to VP9, NO I GOT TO FUCKING DROP THE FILE AND JUST THEN I CAN FUCKING CHANGE IT

Thanks for the product

also there is a weird bug when you encode a file and forget to "choose audio" and if you dont choose an audio settings and it set by default to "None"the encoder will fail.... either on vp9 or av1 

HOLYSHITTT DUDE
I am so fucking mad dude, you literally cant even see buttons in the new ui. I guess its nice that there is a new queue system 

also you cant auto save last settings :// its pretty annoying and I love this program. I havent open a single code line since the BASIC days in 1994

![74ed446f4a14be99dbe050f2b1c1954922483a9f926b3e3df1875a3dabc64b52](https://user-images.githubusercontent.com/76830778/103433564-bde97400-4bfb-11eb-8e7f-a4979f9b42a8.jpg)

![1569497390421](https://user-images.githubusercontent.com/76830778/103433561-add19480-4bfb-11eb-8381-7127f7bc8455.jpg)

Is it possible to get 
a> Remove the thing that doesnt let you change from HEVC to others 
b> Old UI the new is fucking disgusting 
c> get people to get newer builds of ffmpeg with newer nightly updates of AV1's encoders 
e> options to save last profiles

**Comment by cdgriffith** [comment]
Ah, some honest feedback, I enjoyed your candor good sir. 

A) You want to change what you're encoding before you have something selected to encode??? Weird. 😜 Will add that as long term feature request in separate issue. Isn't an easy thing to change.

2) It's like a facebook update. In time you'll learn to love it, and then get more mad when it changes again. (Adding option to go back to old bubbly style in settings in 4.1.0) 

-) I dream about that myself.

𓀱) There is a "New Profile" button on the top right to save your current settings and will reapply them all the time. However I do see the benefit of having a "No Profile" setting, so that it doesn't change it back to defaults, and just leaves it as last applied.

**Comment by forart** [comment]
@GitKike98 You have absolutely no idea of what a "disgusting" interface is, IMHO:
![axiom](https://raw.githubusercontent.com/MattMcManis/Axiom/master/images/axiom.png)

(sorry @MattMcManis)

**Comment by Hrxn** [comment]
Just ignore the dumb troll attempt..

**Comment by j-mas** [comment]
The User interface is one of the best I ever saw! 👍

**Comment by jeremysgates** [comment]
@cdgriffith, personally I think the user interface is very clean and easy to use.  I'm also enjoying the profile selection and queueing system.

**Comment by seighail3** [comment]
> Just ignore the dumb troll attempt..

You are a troll yourelf.... I will just ignore you.

**Comment by cdgriffith** [comment]
Setting to change back to thicc UI in 4.1.0  Adding #170 and #171 for other ideas.
