### ISSUE TITLE
Support for Apple Silicon M1 encoders

### ISSUE THREAD

**Issue by singhkays** [cdgriffith/FastFlix#196]
Hi, do you have plans to support the Apple M1 hardware encoders that are supported in ffmpeg? h264_videotoolbox for H.264, hevc_videotoolbox for H.265

These are available in FFmpeg builds
https://trac.ffmpeg.org/wiki/HWAccelIntro#VideoToolbox

**Comment by cdgriffith** [comment]
I do not have a Mac even for testing, so nothing I could well vet, but I am not opposed to adding hardware acceleration options. I am actually working on NVENC HEVC capabilities at the moment. 

If you (or anyone) has access to one, please provide the output of: 

```
ffmpeg -h encoder=hevc_videotoolbox
```

and the configuration of: 

```
ffmpeg -version
```

 Can also provide `h264_videotoolbox`, but honestly I am not really working towards adding more H.264 at this time

**Comment by singhkays** [comment]
I'm happy to help test this as well as if you can build a native Apple Silicon build. Here are the outputs you requested

```
➜  ~ ffmpeg -h encoder=hevc_videotoolbox
ffmpeg version git-2021-01-09-42ee389 Copyright (c) 2000-2021 the FFmpeg developers
  built with Apple clang version 12.0.0 (clang-1200.0.32.28)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/HEAD-42ee389_6 --enable-shared --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libaom --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-libsnappy --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-demuxer=dash --disable-libjack --disable-indev=jack --enable-opencl --enable-videotoolbox --disable-htmlpages --enable-libfdk-aac --enable-nonfree
  libavutil      56. 63.100 / 56. 63.100
  libavcodec     58.115.102 / 58.115.102
  libavformat    58. 65.101 / 58. 65.101
  libavdevice    58. 11.103 / 58. 11.103
  libavfilter     7. 95.100 /  7. 95.100
  libswscale      5.  8.100 /  5.  8.100
  libswresample   3.  8.100 /  3.  8.100
  libpostproc    55.  8.100 / 55.  8.100
Encoder hevc_videotoolbox [VideoToolbox H.265 Encoder]:
    General capabilities: delay hardware
    Threading capabilities: none
    Supported pixel formats: videotoolbox_vld nv12 yuv420p p010le
hevc_videotoolbox AVOptions:
  -profile           <int>        E..V....... Profile (from 0 to 3) (default 0)
     main            1            E..V....... Main Profile
     main10          2            E..V....... Main10 Profile
  -allow_sw          <boolean>    E..V....... Allow software encoding (default false)
  -require_sw        <boolean>    E..V....... Require software encoding (default false)
  -realtime          <boolean>    E..V....... Hint that encoding should happen in real-time if not faster (e.g. capturing from camera). (default false)
  -frames_before     <boolean>    E..V....... Other frames will come before the frames in this session. This helps smooth concatenation issues. (default false)
  -frames_after      <boolean>    E..V....... Other frames will come after the frames in this session. This helps smooth concatenation issues. (default false)
```

```
➜  ~ ffmpeg -version
ffmpeg version git-2021-01-09-42ee389 Copyright (c) 2000-2021 the FFmpeg developers
built with Apple clang version 12.0.0 (clang-1200.0.32.28)
configuration: --prefix=/usr/local/Cellar/ffmpeg/HEAD-42ee389_6 --enable-shared --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libaom --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-libsnappy --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-demuxer=dash --disable-libjack --disable-indev=jack --enable-opencl --enable-videotoolbox --disable-htmlpages --enable-libfdk-aac --enable-nonfree
libavutil      56. 63.100 / 56. 63.100
libavcodec     58.115.102 / 58.115.102
libavformat    58. 65.101 / 58. 65.101
libavdevice    58. 11.103 / 58. 11.103
libavfilter     7. 95.100 /  7. 95.100
libswscale      5.  8.100 /  5.  8.100
libswresample   3.  8.100 /  3.  8.100
libpostproc    55.  8.100 / 55.  8.100
```

```
➜  ~ ffmpeg -h encoder=h264_videotoolbox
ffmpeg version git-2021-01-09-42ee389 Copyright (c) 2000-2021 the FFmpeg developers
  built with Apple clang version 12.0.0 (clang-1200.0.32.28)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/HEAD-42ee389_6 --enable-shared --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libaom --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-libsnappy --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-demuxer=dash --disable-libjack --disable-indev=jack --enable-opencl --enable-videotoolbox --disable-htmlpages --enable-libfdk-aac --enable-nonfree
  libavutil      56. 63.100 / 56. 63.100
  libavcodec     58.115.102 / 58.115.102
  libavformat    58. 65.101 / 58. 65.101
  libavdevice    58. 11.103 / 58. 11.103
  libavfilter     7. 95.100 /  7. 95.100
  libswscale      5.  8.100 /  5.  8.100
  libswresample   3.  8.100 /  3.  8.100
  libpostproc    55.  8.100 / 55.  8.100
Encoder h264_videotoolbox [VideoToolbox H.264 Encoder]:
    General capabilities: delay
    Threading capabilities: none
    Supported pixel formats: videotoolbox_vld nv12 yuv420p
h264_videotoolbox AVOptions:
  -profile           <int>        E..V....... Profile (from 0 to 5) (default 0)
     baseline        1            E..V....... Baseline Profile
     main            2            E..V....... Main Profile
     high            3            E..V....... High Profile
     extended        4            E..V....... Extend Profile
  -level             <int>        E..V....... Level (from 0 to 52) (default 0)
     1.3             13           E..V....... Level 1.3, only available with Baseline Profile
     3.0             30           E..V....... Level 3.0
     3.1             31           E..V....... Level 3.1
     3.2             32           E..V....... Level 3.2
     4.0             40           E..V....... Level 4.0
     4.1             41           E..V....... Level 4.1
     4.2             42           E..V....... Level 4.2
     5.0             50           E..V....... Level 5.0
     5.1             51           E..V....... Level 5.1
     5.2             52           E..V....... Level 5.2
  -coder             <int>        E..V....... Entropy coding (from 0 to 2) (default 0)
     cavlc           1            E..V....... CAVLC entropy coding
     vlc             1            E..V....... CAVLC entropy coding
     cabac           2            E..V....... CABAC entropy coding
     ac              2            E..V....... CABAC entropy coding
  -a53cc             <boolean>    E..V....... Use A53 Closed Captions (if available) (default true)
  -allow_sw          <boolean>    E..V....... Allow software encoding (default false)
  -require_sw        <boolean>    E..V....... Require software encoding (default false)
  -realtime          <boolean>    E..V....... Hint that encoding should happen in real-time if not faster (e.g. capturing from camera). (default false)
  -frames_before     <boolean>    E..V....... Other frames will come before the frames in this session. This helps smooth concatenation issues. (default false)
  -frames_after      <boolean>    E..V....... Other frames will come after the frames in this session. This helps smooth concatenation issues. (default false)
```

**Comment by cdgriffith** [comment]
wow not a lot of options, makes it easier for moi! 

For a build have to wait on github actions support for it: https://github.com/actions/virtual-environments/issues/2187

**Comment by singhkays** [comment]
> For a build have to wait on github actions support for it: actions/virtual-environments#2187

Ooh..that's going to take a while :| Is it possible for me to compile a native build myself?

**Comment by cdgriffith** [comment]
If you goal is to just run it, should be able to do that:  https://github.com/cdgriffith/FastFlix#running-from-source-code  Good first step to make sure of either way, I do not know if all the packages are supported on the new macs yet. 

If you want to actually do the work to make a redistributable executable, you could go through the steps in the build script and see how it works out: https://github.com/cdgriffith/FastFlix/blob/master/.github/workflows/build_mac.yaml

**Comment by singhkays** [comment]
> If you goal is to just run it, should be able to do that: https://github.com/cdgriffith/FastFlix#running-from-source-code Good first step to make sure of either way, I do not know if all the packages are supported on the new macs yet.

Yep, I tried this already with Python 3.9.1 (Apple Silicon installer). Looks like the Python itself is still "Intel" architecture and hasn't transitioned to Apple Silicon. I'm assuming building the redistributable will also be an Intel version.

**Comment by forart** [comment]
Interesting readings about Apple Silicon software porting:
https://hacks.mozilla.org/2021/01/porting-firefox-to-apple-silicon/

https://corellium.com/blog/linux-m1

**Comment by moonwhaler** [comment]
Personally, I don't mind using Fastflix with Rosetta 2. What is important to me, as mentioned in the first post, is the use of "Apple Silicon" encoders. What I did was to download the pre compiled version of ffmpeg from here: https://www.osxexperts.net/

And then poiting FastFlix to that location. If you look into top/ps/activity monitor and expand the process of FastFlix / Python you should recognize a "Apple Silicon" process while encoding. Works for me. 

Plus, the binary from the URL above also includes support ARM Neon, which speeds up the encoding significantly!

**Comment by jannisberry** [comment]
ffmpeg version 4.4.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with Apple clang version 13.0.0 (clang-1300.0.29.3)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/4.4.1_2 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-avresample --enable-videotoolbox
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Encoder hevc_videotoolbox [VideoToolbox H.265 Encoder]:
    General capabilities: delay hardware 
    Threading capabilities: none
    Supported pixel formats: videotoolbox_vld nv12 yuv420p bgra p010le
hevc_videotoolbox AVOptions:
  -profile           <int>        E..V....... Profile (from 0 to 3) (default 0)
     main            1            E..V....... Main Profile
     main10          2            E..V....... Main10 Profile
  -alpha_quality     <double>     E..V....... Compression quality for the alpha channel (from 0 to 1) (default 0)
  -allow_sw          <boolean>    E..V....... Allow software encoding (default false)
  -require_sw        <boolean>    E..V....... Require software encoding (default false)
  -realtime          <boolean>    E..V....... Hint that encoding should happen in real-time if not faster (e.g. capturing from camera). (default false)
  -frames_before     <boolean>    E..V....... Other frames will come before the frames in this session. This helps smooth concatenation issues. (default false)
  -frames_after      <boolean>    E..V....... Other frames will come after the frames in this session. This helps smooth concatenation issues. (default false)



These are M1 Max and presumably M1 Pro encoders if that would be helpful anywhere


ffmpeg version 4.4.1 Copyright (c) 2000-2021 the FFmpeg developers
built with Apple clang version 13.0.0 (clang-1300.0.29.3)
configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/4.4.1_2 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-avresample --enable-videotoolbox
libavutil      56. 70.100 / 56. 70.100
libavcodec     58.134.100 / 58.134.100
libavformat    58. 76.100 / 58. 76.100
libavdevice    58. 13.100 / 58. 13.100
libavfilter     7.110.100 /  7.110.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  9.100 /  5.  9.100
libswresample   3.  9.100 /  3.  9.100
libpostproc    55.  9.100 / 55.  9.100


and dis ffmpeg version

**Comment by cwills75** [comment]
According to this page:

https://trac.ffmpeg.org/wiki/HWAccelIntro

VideoToolbox does not support CRF, and you have to use -b:v

I've loaded a 4K UHD file into FastFlix on OSX, set my normal options and then copied the raw code into a text editor.  There I changed the video encoder to hevc_videotoolbox.  I also changed the pixel format yuv420p10le to p010le as that is the one supported in the code and added -porfile:v main10 otherwise the files output as 8 bit.   Here are the full commands:

---------------------
"/Applications/ffmpeg" -y      -i "/Users/chadwills/Downloads/s01e01.mkv"   -max_muxing_queue_size 1024 -map 0:0   -c:v hevc_videotoolbox -pix_fmt p010le -profile:v main10      -x265-params "aq-mode=2:repeat-headers=1:strong-intra-smoothing=1:bframes=4:b-adapt=2:frame-threads=0:colorprim=bt2020:transfer=smpte2084:colormatrix=bt2020nc:hdr10_opt=1:master-display=G(8500,39850)B(6550,2300)R(35400,14600)WP(15635,16450)L(10000000,1):max-cll=954,32:hdr10=1:chromaloc=0:pass=1:no-slow-firstpass=1"  -passlogfile "/Users/chadwills/Library/Application Support/FastFlix/temp_978e629a12790a3569349ef8/pass_log_file_83d6b59b114696608d74" -b:v 5000k -preset:v veryfast   -an -sn -dn -f mp4 /dev/null

"/Applications/ffmpeg" -y      -i "/Users/chadwills/Downloads/s01e01.mkv"   -max_muxing_queue_size 1024 -map 0:0   -c:v hevc_videotoolbox -pix_fmt p010le -profile:v main10     -x265-params "aq-mode=2:repeat-headers=1:strong-intra-smoothing=1:bframes=4:b-adapt=2:frame-threads=0:colorprim=bt2020:transfer=smpte2084:colormatrix=bt2020nc:hdr10_opt=1:master-display=G(8500,39850)B(6550,2300)R(35400,14600)WP(15635,16450)L(10000000,1):max-cll=954,32:hdr10=1:chromaloc=0:pass=2"  -passlogfile "/Users/chadwills/Library/Application Support/FastFlix/temp_978e629a12790a3569349ef8/pass_log_file_83d6b59b114696608d74" -b:v 5000k -preset:v veryfast   -map_metadata -1 -map_chapters 0  -map 0:1 -metadata:s:1 title="English" -metadata:s:1 handler="English" -metadata:s:1 language=eng -c:1 copy -default_mode infer_no_subs  "/Users/chadwills/Downloads/s01e01-fastflix-47d3.mkv"
---------------------

Upon running running the 2-step encode, one at a time, here is what is output:

---------------------
chadwills@Chads-MBP /Applications % "/Applications/ffmpeg" -y      -i "/Users/chadwills/Downloads/s01e01.mkv"   -max_muxing_queue_size 1024 -map 0:0   -c:v hevc_videotoolbox -pix_fmt p010le -profile:v main10      -x265-params "aq-mode=2:repeat-headers=1:strong-intra-smoothing=1:bframes=4:b-adapt=2:frame-threads=0:colorprim=bt2020:transfer=smpte2084:colormatrix=bt2020nc:hdr10_opt=1:master-display=G(8500,39850)B(6550,2300)R(35400,14600)WP(15635,16450)L(10000000,1):max-cll=954,32:hdr10=1:chromaloc=0:pass=1:no-slow-firstpass=1"  -passlogfile "/Users/chadwills/Library/Application Support/FastFlix/temp_978e629a12790a3569349ef8/pass_log_file_83d6b59b114696608d74" -b:v 5000k -preset:v veryfast   -an -sn -dn -f mp4 /dev/null
ffmpeg version N-106452-g7fbf1dd47e-tessus Copyright (c) 2000-2022 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.17)
  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvmaf --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay
  libavutil      57. 24.101 / 57. 24.101
  libavcodec     59. 25.100 / 59. 25.100
  libavformat    59. 20.101 / 59. 20.101
  libavdevice    59.  6.100 / 59.  6.100
  libavfilter     8. 29.100 /  8. 29.100
  libswscale      6.  6.100 /  6.  6.100
  libswresample   4.  6.100 /  4.  6.100
  libpostproc    56.  5.100 / 56.  5.100
Input #0, matroska,webm, from '/Users/chadwills/Downloads/s01e01.mkv':
  Metadata:
    encoder         : libebml v1.4.2 + libmatroska v1.6.4
    creation_time   : 2021-05-03T22:35:22.000000Z
  Duration: 00:03:25.34, start: 0.000000, bitrate: 16911 kb/s
  Stream #0:0: Video: hevc (Main 10), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 3840x2160 [SAR 1:1 DAR 16:9], 24 fps, 24 tbr, 1k tbn (default)
    Metadata:
      BPS             : 16653745
      DURATION        : 00:03:25.334000000
      NUMBER_OF_FRAMES: 4928
      NUMBER_OF_BYTES : 427447514
      _STATISTICS_WRITING_APP: mkvmerge v56.1.0 ('My Friend') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-05-03 22:35:22
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1(eng): Audio: eac3, 48000 Hz, 5.1(side), fltp, 256 kb/s (default)
    Metadata:
      title           : English
      BPS             : 256000
      DURATION        : 00:03:25.344000000
      NUMBER_OF_FRAMES: 6417
      NUMBER_OF_BYTES : 6571008
      _STATISTICS_WRITING_APP: mkvmerge v56.1.0 ('My Friend') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-05-03 22:35:22
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:2(eng): Subtitle: subrip
    Metadata:
      title           : English (SDH)
      BPS             : 13
      DURATION        : 00:03:13.667000000
      NUMBER_OF_FRAMES: 20
      NUMBER_OF_BYTES : 332
      _STATISTICS_WRITING_APP: mkvmerge v56.1.0 ('My Friend') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-05-03 22:35:22
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
Codec AVOption x265-params (set the x265 configuration using a :-separated list of key=value parameters) specified for output file #0 (/dev/null) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
Codec AVOption preset (Configuration preset) specified for output file #0 (/dev/null) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> hevc (hevc_videotoolbox))
Press [q] to stop, [?] for help
[hevc_videotoolbox @ 0x7f94c610ef80] Transfer function smpte2084 is not supported.
Output #0, mp4, to '/dev/null':
  Metadata:
    encoder         : Lavf59.20.101
  Stream #0:0: Video: hevc (hev1 / 0x31766568), p010le(tv, bt2020nc/bt2020/smpte2084, progressive), 3840x2160 [SAR 1:1 DAR 16:9], q=2-31, 5000 kb/s, 24 fps, 12288 tbn (default)
    Metadata:
      BPS             : 16653745
      DURATION        : 00:03:25.334000000
      NUMBER_OF_FRAMES: 4928
      NUMBER_OF_BYTES : 427447514
      _STATISTICS_WRITING_APP: mkvmerge v56.1.0 ('My Friend') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-05-03 22:35:22
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      encoder         : Lavc59.25.100 hevc_videotoolbox
frame= 4928 fps= 52 q=-0.0 Lsize=  124350kB time=00:03:25.29 bitrate=4962.1kbits/s speed=2.16x       
video:124327kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.018822%
chadwills@Chads-MBP /Applications % "/Applications/ffmpeg" -y      -i "/Users/chadwills/Downloads/s01e01.mkv"   -max_muxing_queue_size 1024 -map 0:0   -c:v hevc_videotoolbox -pix_fmt p010le -profile:v main10     -x265-params "aq-mode=2:repeat-headers=1:strong-intra-smoothing=1:bframes=4:b-adapt=2:frame-threads=0:colorprim=bt2020:transfer=smpte2084:colormatrix=bt2020nc:hdr10_opt=1:master-display=G(8500,39850)B(6550,2300)R(35400,14600)WP(15635,16450)L(10000000,1):max-cll=954,32:hdr10=1:chromaloc=0:pass=2"  -passlogfile "/Users/chadwills/Library/Application Support/FastFlix/temp_978e629a12790a3569349ef8/pass_log_file_83d6b59b114696608d74" -b:v 5000k -preset:v veryfast   -map_metadata -1 -map_chapters 0  -map 0:1 -metadata:s:1 title="English" -metadata:s:1 handler="English" -metadata:s:1 language=eng -c:1 copy -default_mode infer_no_subs  "/Users/chadwills/Downloads/s01e01-fastflix-47d3.mkv"
ffmpeg version N-106452-g7fbf1dd47e-tessus Copyright (c) 2000-2022 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.17)
  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvmaf --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay
  libavutil      57. 24.101 / 57. 24.101
  libavcodec     59. 25.100 / 59. 25.100
  libavformat    59. 20.101 / 59. 20.101
  libavdevice    59.  6.100 / 59.  6.100
  libavfilter     8. 29.100 /  8. 29.100
  libswscale      6.  6.100 /  6.  6.100
  libswresample   4.  6.100 /  4.  6.100
  libpostproc    56.  5.100 / 56.  5.100
Input #0, matroska,webm, from '/Users/chadwills/Downloads/s01e01.mkv':
  Metadata:
    encoder         : libebml v1.4.2 + libmatroska v1.6.4
    creation_time   : 2021-05-03T22:35:22.000000Z
  Duration: 00:03:25.34, start: 0.000000, bitrate: 16911 kb/s
  Stream #0:0: Video: hevc (Main 10), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 3840x2160 [SAR 1:1 DAR 16:9], 24 fps, 24 tbr, 1k tbn (default)
    Metadata:
      BPS             : 16653745
      DURATION        : 00:03:25.334000000
      NUMBER_OF_FRAMES: 4928
      NUMBER_OF_BYTES : 427447514
      _STATISTICS_WRITING_APP: mkvmerge v56.1.0 ('My Friend') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-05-03 22:35:22
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1(eng): Audio: eac3, 48000 Hz, 5.1(side), fltp, 256 kb/s (default)
    Metadata:
      title           : English
      BPS             : 256000
      DURATION        : 00:03:25.344000000
      NUMBER_OF_FRAMES: 6417
      NUMBER_OF_BYTES : 6571008
      _STATISTICS_WRITING_APP: mkvmerge v56.1.0 ('My Friend') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-05-03 22:35:22
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:2(eng): Subtitle: subrip
    Metadata:
      title           : English (SDH)
      BPS             : 13
      DURATION        : 00:03:13.667000000
      NUMBER_OF_FRAMES: 20
      NUMBER_OF_BYTES : 332
      _STATISTICS_WRITING_APP: mkvmerge v56.1.0 ('My Friend') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2021-05-03 22:35:22
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
Codec AVOption preset (Configuration preset) specified for output file #0 (/Users/chadwills/Downloads/s01e01-fastflix-47d3.mkv) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> hevc (hevc_videotoolbox))
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[hevc_videotoolbox @ 0x7fc687010540] Transfer function smpte2084 is not supported.
Output #0, matroska, to '/Users/chadwills/Downloads/s01e01-fastflix-47d3.mkv':
  Metadata:
    encoder         : Lavf59.20.101
  Stream #0:0: Video: hevc, p010le(tv, bt2020nc/bt2020/smpte2084, progressive), 3840x2160 [SAR 1:1 DAR 16:9], q=2-31, 5000 kb/s, 24 fps, 1k tbn (default)
    Metadata:
      encoder         : Lavc59.25.100 hevc_videotoolbox
  Stream #0:1(eng): Audio: eac3 ([0] [0][0] / 0x2000), 48000 Hz, 5.1(side), fltp, 256 kb/s (default)
    Metadata:
      title           : English
      handler         : English
frame= 4928 fps= 52 q=-0.0 Lsize=  130841kB time=00:03:25.31 bitrate=5220.6kbits/s speed=2.16x    
video:124327kB audio:6417kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.073825%
---------------------

Looking at the output file vs. the original with MediaInfo, the output file is mising HDR format: SMPTE ST 2086, HDR10 Compatible, Mastering display luminance, MaxCLL and MaxFALL info.  Here is some other info I've found on FFmpeg VideoToolbox, I don't know if it's relevant.

https://github.com/FFmpeg/FFmpeg/commit/391b67fcb58f95b5cc65b75070fd9a3dce4f8ac6

There are a couple of errors that come up during the encodes.  The first is in yellow:

Codec AVOption preset (Configuration preset) specified for output file #0 (/Users/chadwills/Downloads/s01e01-fastflix-47d3.mkv) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.

The second is in red:

[hevc_videotoolbox @ 0x7fc687010540] Transfer function smpte2084 is not supported.

I don't know what either of those mean.  Even after removing :transfer=smpte2084 from the raw commands, the transfer function error shows.  If any of this helps to get Videotoolbox encoding in FastFlix that would be great.  The encoding speed on my Macbook Pro with M1 Pro using Videotoolbox is over 5x faster than without.  Also, if anyone knows how to get rid of the FFmpeg errors and get the HDR format information, Master display, MaxCLL, MaxFALL in the output file, that would be appreciated.  I can guinea pig some stuff if I'm told what commands to use.

**Comment by cdgriffith** [comment]
I have created a new branch with hevc_videotoolbox support. Any brave users willing to test would be greatly appreciated as I don't have a box to try it on. 

```
git clone https://github.com/cdgriffith/FastFlix.git
cd FastFlix
git checkout videotoolbox
python3 -m venv venv
. venv/bin/activate
pip install -r requirements.txt
python -m fastflix
``` 

There should be a new dropdown option for HEVC videotoolbox. Please test to make sure it works / try to break it!

**Comment by E-t-z** [comment]
Nice, will try it out in upcoming days. :)

**Comment by cdgriffith** [comment]
> By any chance, could you add avc (h264_videotoolbox) support as well?

Yup, will add that if this one works well. Just easier to do one at a time.

**Comment by cdgriffith** [comment]
@E-t-z added support for h264 in that branch as well if you can test it out!

**Comment by E-t-z** [comment]
@cdgriffith will take a look on Sunday, sorry for the delay.

h265_videotoolbox seemed to work quite well.

**Comment by cdgriffith** [comment]
H265 and H264 added with https://github.com/cdgriffith/FastFlix/releases/tag/4.9.0 !

**Comment by sublimal** [comment]
How do I select videotoolbox encoder?
![image](https://user-images.githubusercontent.com/4757622/174063286-d23a4652-b687-4041-a91b-d5c0a33eea24.png)

Looking at the code I suspect the issue is [`requires`](https://github.com/cdgriffith/FastFlix/blob/master/fastflix/encoders/hevc_videotoolbox/main.py#L9) which should be `videotoolbox` as per ffmpeg version/configuration provided above, eg `--enable-videotoolbox` in:
```
% ffmpeg -version
ffmpeg version 5.0.1 Copyright (c) 2000-2022 the FFmpeg developers
built with Apple clang version 13.1.6 (clang-1316.0.21.2.5)
configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/5.0.1-with-options_2 --enable-shared --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libaom --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-libsnappy --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-demuxer=dash --enable-opencl --enable-audiotoolbox --enable-videotoolbox --enable-neon --disable-htmlpages
```

**Comment by cdgriffith** [comment]
You are totally right @sublimal, good catch, thank you!

**Comment by cdgriffith** [comment]
Ok hopefully that did it, please let me know if not working with https://github.com/cdgriffith/FastFlix/releases/tag/4.9.4 !
