### ISSUE TITLE
Error loading Python lib on my Mac

### ISSUE THREAD

**Issue by nanni61** [cdgriffith/FastFlix#215]
[1398] Error loading Python lib '/var/folders/jn/3px6xcnn6xgbp5_4t1_ldx3h0000gn/T/_MEIQhvjJx/libpython3.8.dylib': dlopen: dlopen(/var/folders/jn/3px6xcnn6xgbp5_4t1_ldx3h0000gn/T/_MEIQhvjJx/libpython3.8.dylib, 10): Symbol not found: ____chkstk_darwin
  Referenced from: /var/folders/jn/3px6xcnn6xgbp5_4t1_ldx3h0000gn/T/_MEIQhvjJx/libintl.8.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /var/folders/jn/3px6xcnn6xgbp5_4t1_ldx3h0000gn/T/_MEIQhvjJx/libintl.8.dylib

**Comment by cdgriffith** [comment]
I don't have a OS X machine to try and debug this with, so anyone else that can help would appreciate it!

**Comment by moonwhaler** [comment]
I am using a Mac M1 (Air) (MacOS version 11.3.1 (20E241)) with Python 2.7.16 - I have never seen this kind of error. Maybe @nanni61 should specify which version of MacOS and Python is being used - and what could be done to reproduce this message?

**Comment by nanni61** [comment]
This sw works only from 10.15 onwards. I solved the problem by throwing it in the trash and using something else. And I live happy.

**Comment by cdgriffith** [comment]
FastFlix will try it's best to support maintained version of operation systems that can run Python 3.11 and Pyside6, currently that is macOS 11 onward https://en.wikipedia.org/wiki/MacOS_version_history#Releases . As it sounds like the issue was an outdated OS closing this issue for now. If this comes up with a newer version please leave details here and I will reopen!
