### ISSUE TITLE
FastFlix wont start with DEBUG Conversion worker shutting down

### ISSUE THREAD

**Issue by sclauss** [cdgriffith/FastFlix#220]
OS: Manjaro Linux 
After the last Manjaro system update FastFlix wont start.
I find it very hard to diagnose the problem, as there is barely any output by FastFlix as to what exactly has gone wrong.
The only thing I am getting is:
```
2021-05-06 22:27:41 c fastflix-core[10803] INFO Starting FastFlix 4.2.0
2021-05-06 22:27:41 c fastflix-core[10803] DEBUG Conversion worker shutting down
```
As far as I was able to trace the debug info is, that it seems to have something to do with the GUI being down or unable to run.
Is there any way for me to get any more information out of FastFlix to help fix this?

**Comment by cdgriffith** [comment]
Weird that's all it gives, guessing there is some issue with QT version stuff.   First try with `QT_DEBUG_PLUGINS=1 ./FastFlix` when running to see if that gives any more info. 

You will probably end up having to run from source code to see the full error. (Can update with instructions after dinner) 

previous issues I've seen with linux https://github.com/cdgriffith/FastFlix/wiki/Common-questions-and-problems#qtqpaplugin-could-not-load-the-qt-platform-plugin-xcb-in--even-though-it-was-found

**Comment by cdgriffith** [comment]
Oh, forgot I put those instructions in the readme, yay me. https://github.com/cdgriffith/FastFlix#running-from-source-code

**Comment by ryaniskira** [comment]
I am having the same issue, here is the error I get after running from source:

```    
WARNING: en is not a supported language, defaulting to eng
2021-05-06 23:05:58 Patchouli-Knowledge fastflix-core[989232] INFO Starting FastFlix 4.2.0
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kira/Desktop/FastFlix/fastflix/entry.py", line 31, in separate_app_process
    from fastflix.application import start_app
  File "/home/kira/Desktop/FastFlix/fastflix/application.py", line 18, in <module>
    from fastflix.widgets.container import Container
  File "/home/kira/Desktop/FastFlix/fastflix/widgets/container.py", line 25, in <module>
    from fastflix.widgets.main import Main
  File "/home/kira/Desktop/FastFlix/fastflix/widgets/main.py", line 51, in <module>
    from fastflix.widgets.video_options import VideoOptions
  File "/home/kira/Desktop/FastFlix/fastflix/widgets/video_options.py", line 23, in <module>
    from fastflix.widgets.panels.audio_panel import AudioList
  File "/home/kira/Desktop/FastFlix/fastflix/widgets/panels/audio_panel.py", line 18, in <module>
    language_list = sorted((k for k, v in Lang._data["name"].items() if v["pt2B"] and v["pt1"]), key=lambda x: x.lower())
  File "/home/kira/Desktop/FastFlix/fastflix/widgets/panels/audio_panel.py", line 18, in <genexpr>
    language_list = sorted((k for k, v in Lang._data["name"].items() if v["pt2B"] and v["pt1"]), key=lambda x: x.lower())
KeyError: 'pt2B'
2021-05-06 23:05:58 Patchouli-Knowledge fastflix-core[989232] DEBUG Conversion worker shutting down
```

**Comment by sclauss** [comment]
Running from source I get the same 
```
2021-05-07 13:01:39 c fastflix-core[10250] INFO Starting FastFlix 4.2.0
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/stefan/clonedrepos/FastFlix/fastflix/entry.py", line 31, in separate_app_process
    from fastflix.application import start_app
  File "/home/stefan/clonedrepos/FastFlix/fastflix/application.py", line 18, in <module>
    from fastflix.widgets.container import Container
  File "/home/stefan/clonedrepos/FastFlix/fastflix/widgets/container.py", line 25, in <module>
    from fastflix.widgets.main import Main
  File "/home/stefan/clonedrepos/FastFlix/fastflix/widgets/main.py", line 51, in <module>
    from fastflix.widgets.video_options import VideoOptions
  File "/home/stefan/clonedrepos/FastFlix/fastflix/widgets/video_options.py", line 23, in <module>
    from fastflix.widgets.panels.audio_panel import AudioList
  File "/home/stefan/clonedrepos/FastFlix/fastflix/widgets/panels/audio_panel.py", line 18, in <module>
    language_list = sorted((k for k, v in Lang._data["name"].items() if v["pt2B"] and v["pt1"]), key=lambda x: x.lower())
  File "/home/stefan/clonedrepos/FastFlix/fastflix/widgets/panels/audio_panel.py", line 18, in <genexpr>
    language_list = sorted((k for k, v in Lang._data["name"].items() if v["pt2B"] and v["pt1"]), key=lambda x: x.lower())
KeyError: 'pt2B'
2021-05-07 13:01:39 c fastflix-core[10250] DEBUG Conversion worker shutting down
```

**Comment by sclauss** [comment]
Thank you!
That seems to have solved it.
Do you have any idea when you will be publishing that next release? Or is there any way of me creating a build myself?

**Comment by cdgriffith** [comment]
The build script I use is public and all the commands are there (linking in case it changes): https://github.com/cdgriffith/FastFlix/blob/master/.github/workflows/build_linux.yaml

Boils down to:

```
python -m pip install --upgrade pip setuptools --ignore-installed
python -m pip install --upgrade wheel typing_extensions
python -m pip install -r requirements-build.txt
python -m pip install --upgrade pyqt5-tools
cp $(python -c "import iso639; print(iso639.mapping.TABLE_PATH)") iso-639-3.tab
cp $(python -c "import iso639; print(iso639.mapping.MAPPING_PATH)") iso-639-3.json        
pyinstaller FastFlix_Nix_OneFile.spec
```

That will make the execuatble at `dist/FastFlix`

Honestly I don't know if the next release will solve the issue related to that version of linux. Could be a pyinstaller thing, QT thing or who knows what. Let me know if you have issues after building it!

**Comment by sclauss** [comment]
Thanks for that. But it seems the pyinstaller has some problems.
```
17 INFO: PyInstaller: 4.2
17 INFO: Python: 3.9.4
18 INFO: Platform: Linux-5.11.18-1-MANJARO-x86_64-with-glibc2.33
20 INFO: UPX is not available.
45 INFO: Extending PYTHONPATH with paths
['/home/stefan/clonedrepos/FastFlix']
47 INFO: checking Analysis
47 INFO: Building Analysis because Analysis-00.toc is non existent
47 INFO: Initializing module dependency graph...
48 INFO: Caching module graph hooks...
50 WARNING: Several hooks defined for module 'win32ctypes.core'. Please take care they do not conflict.
51 INFO: Analyzing base_library.zip ...
1141 INFO: Processing pre-find module path hook distutils from '/home/stefan/clonedrepos/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/hooks/pre_find_module_path/hook-distutils.py'.
1141 INFO: distutils: retargeting to non-venv dir '/usr/lib/python3.9'
2156 INFO: Caching module dependency graph...
2198 INFO: running Analysis Analysis-00.toc
2222 INFO: Analyzing fastflix/__main__.py
2396 INFO: Processing pre-safe import module hook urllib3.packages.six.moves from '/home/stefan/clonedrepos/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-urllib3.packages.six.moves.py'.
3149 INFO: Processing pre-safe import module hook win32com from '/home/stefan/clonedrepos/FastFlix/venv/lib/python3.9/site-packages/_pyinstaller_hooks_contrib/hooks/pre_safe_import_module/hook-win32com.py'.
3978 INFO: Analyzing hidden import 'pydantic.generics'
3990 INFO: Analyzing hidden import 'pydantic.env_settings'
3990 INFO: Analyzing hidden import 'pydantic._hypothesis_plugin'
3990 INFO: Analyzing hidden import 'pydantic.annotated_types'
3990 INFO: Analyzing hidden import 'pydantic.types'
3990 INFO: Analyzing hidden import 'pydantic.color'
3990 INFO: Analyzing hidden import 'pydantic.dataclasses'
3990 INFO: Analyzing hidden import 'pydantic.validators'
3990 INFO: Analyzing hidden import 'pydantic.networks'
3990 INFO: Analyzing hidden import 'pydantic.tools'
3991 INFO: Analyzing hidden import 'pydantic.datetime_parse'
3991 INFO: Analyzing hidden import 'pydantic.decorator'
3991 INFO: Analyzing hidden import 'pydantic.parse'
3991 INFO: Analyzing hidden import 'pydantic.schema'
3991 INFO: Analyzing hidden import 'pydantic.error_wrappers'
3991 INFO: Analyzing hidden import 'pydantic.errors'
3991 INFO: Analyzing hidden import 'pydantic.json'
3991 INFO: Analyzing hidden import 'pydantic.mypy'
3991 INFO: Analyzing hidden import 'pydantic.version'
3991 INFO: Analyzing hidden import 'colorsys'
3994 INFO: Analyzing hidden import 'typing_extensions'
4029 INFO: Analyzing hidden import 'iso639-lang'
4029 ERROR: Hidden import 'iso639-lang' not found
4029 INFO: Analyzing hidden import 'pyqt5'
4029 ERROR: Hidden import 'pyqt5' not found
4029 INFO: Analyzing hidden import 'python-box'
4029 ERROR: Hidden import 'python-box' not found
4029 INFO: Processing module hooks...
4029 INFO: Loading module hook 'hook-pydantic.py' from '/home/stefan/clonedrepos/FastFlix/venv/lib/python3.9/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
4104 INFO: Loading module hook 'hook-certifi.py' from '/home/stefan/clonedrepos/FastFlix/venv/lib/python3.9/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
4106 INFO: Loading module hook 'hook-appdirs.py' from '/home/stefan/clonedrepos/FastFlix/venv/lib/python3.9/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
4107 INFO: Excluding import of win32com from module appdirs
4108 INFO: Loading module hook 'hook-encodings.py' from '/home/stefan/clonedrepos/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/hooks'...
4137 INFO: Loading module hook 'hook-multiprocessing.util.py' from '/home/stefan/clonedrepos/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/hooks'...
4138 INFO: Excluding import of test from module multiprocessing.util
4138 INFO: Excluding import of test.support from module multiprocessing.util
4138 INFO: Loading module hook 'hook-heapq.py' from '/home/stefan/clonedrepos/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/hooks'...
4139 INFO: Excluding import of doctest from module heapq
4139 INFO: Loading module hook 'hook-PyQt5.QtWidgets.py' from '/home/stefan/clonedrepos/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/hooks'...
ldd: warning: you do not have execution permission for `/home/stefan/clonedrepos/FastFlix/venv/lib/python3.9/site-packages/PyQt5/QtWidgets.abi3.so'
4207 INFO: Loading module hook 'hook-xml.py' from '/home/stefan/clonedrepos/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/hooks'...
4251 INFO: Loading module hook 'hook-pkg_resources.py' from '/home/stefan/clonedrepos/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/hooks'...
4531 WARNING: Hidden import "pkg_resources.py2_warn" not found!
4531 WARNING: Hidden import "pkg_resources.markers" not found!
4532 INFO: Excluding import of __main__ from module pkg_resources
4532 INFO: Loading module hook 'hook-PyQt5.QtGui.py' from '/home/stefan/clonedrepos/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/hooks'...
ldd: warning: you do not have execution permission for `/home/stefan/clonedrepos/FastFlix/venv/lib/python3.9/site-packages/PyQt5/QtGui.abi3.so'
4565 INFO: Loading module hook 'hook-sysconfig.py' from '/home/stefan/clonedrepos/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/hooks'...
4570 INFO: Loading module hook 'hook-difflib.py' from '/home/stefan/clonedrepos/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/hooks'...
4572 INFO: Excluding import of doctest from module difflib
4572 INFO: Loading module hook 'hook-PyQt5.QtCore.py' from '/home/stefan/clonedrepos/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/hooks'...
ldd: warning: you do not have execution permission for `/home/stefan/clonedrepos/FastFlix/venv/lib/python3.9/site-packages/PyQt5/QtCore.abi3.so'
4587 INFO: Loading module hook 'hook-distutils.py' from '/home/stefan/clonedrepos/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/hooks'...
4588 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from '/home/stefan/clonedrepos/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/hooks'...
4589 INFO: Loading module hook 'hook-lib2to3.py' from '/home/stefan/clonedrepos/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/hooks'...
4598 INFO: Loading module hook 'hook-PyQt5.py' from '/home/stefan/clonedrepos/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/hooks'...
4605 INFO: Loading module hook 'hook-pickle.py' from '/home/stefan/clonedrepos/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/hooks'...
4606 INFO: Excluding import of argparse from module pickle
4606 INFO: Loading module hook 'hook-distutils.util.py' from '/home/stefan/clonedrepos/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/hooks'...
4607 INFO: Excluding import of lib2to3.refactor from module distutils.util
4617 INFO: Looking for ctypes DLLs
Traceback (most recent call last):
  File "/home/stefan/clonedrepos/FastFlix/venv/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
  File "/home/stefan/clonedrepos/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/stefan/clonedrepos/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/stefan/clonedrepos/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/building/build_main.py", line 725, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/stefan/clonedrepos/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/building/build_main.py", line 672, in build
    exec(code, spec_namespace)
  File "FastFlix_Nix_OneFile.spec", line 21, in <module>
    a = Analysis(['fastflix/__main__.py'],
  File "/home/stefan/clonedrepos/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/building/build_main.py", line 242, in __init__
    self.__postinit__()
  File "/home/stefan/clonedrepos/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/building/datastruct.py", line 160, in __postinit__
    self.assemble()
  File "/home/stefan/clonedrepos/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/building/build_main.py", line 438, in assemble
    ctypes_binaries = scan_code_for_ctypes(co)
  File "/home/stefan/clonedrepos/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/depend/utils.py", line 145, in scan_code_for_ctypes
    binaries = _resolveCtypesImports(binaries)
  File "/home/stefan/clonedrepos/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/depend/utils.py", line 319, in _resolveCtypesImports
    load_ldconfig_cache()
  File "/home/stefan/clonedrepos/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/depend/utils.py", line 402, in load_ldconfig_cache
    path = m.groups()[-1]
AttributeError: 'NoneType' object has no attribute 'groups'
```
I did check if iso639-lang, python-box and pyqt5 are installed and it seems like they are.

**Comment by cdgriffith** [comment]
@sclauss error in Pyinstaller 4.2 it seems. 

```
pip install "pyinstaller==4.3" --upgrade
```

Also make sure on Manjaro that binutils is installed. Was able to get it to work on there after those changes.

**Comment by sclauss** [comment]
Thank you for your efforts. binutils was already installed and with pyinstaller 4.3 the build process at least results in a file, even though it is about 20 MiB larger than your latest release and the build log shows almost the same amount of errors and quite a few warnings as well.
After trying to squash warning after warning (I can not, for some reason, get rid of the iso639-lang, python-box and pyqt5 errors) for a few hours (I am still very very new to all of this) I am going to call it quits for today at least. 
If you want me to give you any more of those build logs, I would be happy to.
Maybe I will be able to find some time tomorrow to continue this endeavour (especially if you are).
Was the file that you were able to build on Manjaro runnable as well? Could you send it to me, so that I can check it on my system?

**Comment by cdgriffith** [comment]
Pyinstaller always has plenty of warnings, and those three errors have shown up for me without issue as well. 

Version of Majaro I am trying this on: 

```
5.10.34-1-MANJARO

LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	21.0.4
Codename:	Ornara
```


Lets make sure all the requirement versions are ok for sure. 

```
# Will get errors about pyqt5-tools and pyqt5-plugins, ignore
pip install -r requirements-build.txt --force --upgrade  
pip install "pyinstaller==4.3" --force --upgrade
pyinstaller FastFlix_Nix_OneFile.spec 
```

<details>
<summary>Pyinstaller Log</summary>
<pre>
30 INFO: PyInstaller: 4.3
30 INFO: Python: 3.9.4
33 INFO: Platform: Linux-5.10.34-1-MANJARO-x86_64-with-glibc2.33
34 INFO: UPX is not available.
78 INFO: Extending PYTHONPATH with paths
['/home/james/FastFlix']
82 INFO: checking Analysis
86 INFO: Building because hiddenimports changed
87 INFO: Initializing module dependency graph...
87 INFO: Caching module graph hooks...
89 WARNING: Several hooks defined for module 'win32ctypes.core'. Please take care they do not conflict.
90 INFO: Analyzing base_library.zip ...
1800 INFO: Processing pre-find module path hook distutils from '/home/james/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/hooks/pre_find_module_path/hook-distutils.py'.
1800 INFO: distutils: retargeting to non-venv dir '/usr/lib/python3.9'
2630 INFO: Caching module dependency graph...
2758 INFO: running Analysis Analysis-00.toc
2811 INFO: Analyzing fastflix/__main__.py
3067 INFO: Processing pre-safe import module hook urllib3.packages.six.moves from '/home/james/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-urllib3.packages.six.moves.py'.
4098 INFO: Processing pre-safe import module hook win32com from '/home/james/FastFlix/venv/lib/python3.9/site-packages/_pyinstaller_hooks_contrib/hooks/pre_safe_import_module/hook-win32com.py'.
5543 INFO: Analyzing hidden import 'pydantic.decorator'
5543 INFO: Analyzing hidden import 'pydantic.utils'
5543 INFO: Analyzing hidden import 'pydantic.dataclasses'
5543 INFO: Analyzing hidden import 'pydantic.color'
5543 INFO: Analyzing hidden import 'pydantic.types'
5543 INFO: Analyzing hidden import 'pydantic.fields'
5544 INFO: Analyzing hidden import 'pydantic.class_validators'
5544 INFO: Analyzing hidden import 'pydantic.env_settings'
5544 INFO: Analyzing hidden import 'pydantic.networks'
5544 INFO: Analyzing hidden import 'pydantic.json'
5544 INFO: Analyzing hidden import 'pydantic.parse'
5544 INFO: Analyzing hidden import 'pydantic.datetime_parse'
5544 INFO: Analyzing hidden import 'pydantic.schema'
5544 INFO: Analyzing hidden import 'pydantic.annotated_types'
5545 INFO: Analyzing hidden import 'pydantic.generics'
5550 INFO: Analyzing hidden import 'pydantic.tools'
5550 INFO: Analyzing hidden import 'pydantic.mypy'
5550 INFO: Analyzing hidden import 'pydantic.validators'
5550 INFO: Analyzing hidden import 'pydantic.error_wrappers'
5551 INFO: Analyzing hidden import 'pydantic._hypothesis_plugin'
5551 INFO: Analyzing hidden import 'pydantic.errors'
5551 INFO: Analyzing hidden import 'pydantic.version'
5551 INFO: Analyzing hidden import 'colorsys'
5554 INFO: Analyzing hidden import 'typing_extensions'
5610 INFO: Analyzing hidden import 'iso639-lang'
5611 ERROR: Hidden import 'iso639-lang' not found
5611 INFO: Analyzing hidden import 'pyqt5'
5611 ERROR: Hidden import 'pyqt5' not found
5611 INFO: Analyzing hidden import 'python-box'
5611 ERROR: Hidden import 'python-box' not found
5611 INFO: Processing module hooks...
5611 INFO: Loading module hook 'hook-pydantic.py' from '/home/james/FastFlix/venv/lib/python3.9/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
5737 INFO: Loading module hook 'hook-appdirs.py' from '/home/james/FastFlix/venv/lib/python3.9/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
5739 INFO: Loading module hook 'hook-certifi.py' from '/home/james/FastFlix/venv/lib/python3.9/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
5741 INFO: Loading module hook 'hook-xml.py' from '/home/james/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/hooks'...
5778 INFO: Loading module hook 'hook-PyQt5.QtCore.py' from '/home/james/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/hooks'...
ldd: warning: you do not have execution permission for `/home/james/FastFlix/venv/lib/python3.9/site-packages/PyQt5/QtCore.abi3.so'
5875 INFO: Loading module hook 'hook-PyQt5.QtWidgets.py' from '/home/james/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/hooks'...
ldd: warning: you do not have execution permission for `/home/james/FastFlix/venv/lib/python3.9/site-packages/PyQt5/QtWidgets.abi3.so'
5984 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from '/home/james/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/hooks'...
5985 INFO: Loading module hook 'hook-sysconfig.py' from '/home/james/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/hooks'...
5991 INFO: Loading module hook 'hook-difflib.py' from '/home/james/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/hooks'...
5993 INFO: Loading module hook 'hook-PyQt5.py' from '/home/james/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/hooks'...
6002 INFO: Loading module hook 'hook-distutils.py' from '/home/james/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/hooks'...
6002 INFO: Loading module hook 'hook-pkg_resources.py' from '/home/james/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/hooks'...
6369 WARNING: Hidden import "pkg_resources.py2_warn" not found!
6370 WARNING: Hidden import "pkg_resources.markers" not found!
6371 INFO: Loading module hook 'hook-multiprocessing.util.py' from '/home/james/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/hooks'...
6372 INFO: Loading module hook 'hook-PyQt5.QtGui.py' from '/home/james/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/hooks'...
ldd: warning: you do not have execution permission for `/home/james/FastFlix/venv/lib/python3.9/site-packages/PyQt5/QtGui.abi3.so'
6422 INFO: Loading module hook 'hook-pickle.py' from '/home/james/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/hooks'...
6424 INFO: Loading module hook 'hook-heapq.py' from '/home/james/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/hooks'...
6425 INFO: Loading module hook 'hook-encodings.py' from '/home/james/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/hooks'...
6473 INFO: Loading module hook 'hook-lib2to3.py' from '/home/james/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/hooks'...
6494 INFO: Loading module hook 'hook-distutils.util.py' from '/home/james/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/hooks'...
6519 INFO: Looking for ctypes DLLs
6601 INFO: Analyzing run-time hooks ...
6606 INFO: Including run-time hook '/home/james/FastFlix/venv/lib/python3.9/site-packages/_pyinstaller_hooks_contrib/hooks/rthooks/pyi_rth_certifi.py'
6607 INFO: Including run-time hook '/home/james/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pyqt5.py'
6607 INFO: Including run-time hook '/home/james/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pkgres.py'
6610 INFO: Including run-time hook '/home/james/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py'
6627 INFO: Looking for dynamic libraries
ldd: warning: you do not have execution permission for `/home/james/FastFlix/venv/lib/python3.9/site-packages/PyQt5/QtWidgets.abi3.so'
ldd: warning: you do not have execution permission for `/home/james/FastFlix/venv/lib/python3.9/site-packages/PyQt5/QtGui.abi3.so'
ldd: warning: you do not have execution permission for `/home/james/FastFlix/venv/lib/python3.9/site-packages/PyQt5/QtCore.abi3.so'
ldd: warning: you do not have execution permission for `/usr/lib/libgcc_s.so.1'
ldd: warning: you do not have execution permission for `/usr/lib/libcap.so.2'
10244 INFO: Looking for eggs
10244 INFO: Using Python library /usr/lib/libpython3.9.so.1.0
10252 INFO: Warnings written to /home/james/FastFlix/build/FastFlix_Nix_OneFile/warn-FastFlix_Nix_OneFile.txt
10312 INFO: Graph cross-reference written to /home/james/FastFlix/build/FastFlix_Nix_OneFile/xref-FastFlix_Nix_OneFile.html
10337 INFO: Appending 'datas' from .spec
10343 INFO: checking PYZ
10354 INFO: Building because toc changed
10356 INFO: Building PYZ (ZlibArchive) /home/james/FastFlix/build/FastFlix_Nix_OneFile/PYZ-00.pyz
10823 INFO: Building PYZ (ZlibArchive) /home/james/FastFlix/build/FastFlix_Nix_OneFile/PYZ-00.pyz completed successfully.
10837 INFO: checking PKG
10839 INFO: Building because toc changed
10839 INFO: Building PKG (CArchive) PKG-00.pkg
47286 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
47290 INFO: Bootloader /home/james/FastFlix/venv/lib/python3.9/site-packages/PyInstaller/bootloader/Linux-64bit/run
47290 INFO: checking EXE
47292 INFO: Building because toc changed
47292 INFO: Building EXE from EXE-00.toc
47299 INFO: Appending archive to ELF section in EXE /home/james/FastFlix/dist/FastFlix
47624 INFO: Building EXE from EXE-00.toc completed successfully.
</pre>
</details>

This makes about a 85MB release file (size changes based on system packages in env as pyinstaller is "agressive" in packing things). Should be able to run that directly.  To large to put here so will upload somewhere else and link in a bit

**Comment by sclauss** [comment]
Ok. Thank you again. I do not at all understand what I did differently right now as compared to yesterday, but it works!
The resulting file is about 95 MiB, but it is fully functional. 
Before I close this I have a, hopefully not too weird, question. I would like to contribute to FastFlix. That last time I did any coding in Python was about 10 years ago and very rudimentary (at best). So I would only be able to do very little at the start. And I am still very new to all of this (github, contributing code ...), but I did learn a lot yesterday and had a lot of fun doing it as well. 
What would you recommend I should start learning and understanding so that I might meaningfully contribute sometime in the future?

**Comment by cdgriffith** [comment]
Great to hear it's working! 

For getting started with basic basics people I know have gone from 0 used https://www.codecademy.com/learn/learn-python-3 and ~6 to 12 months later got coding jobs.  If you remember a decent amount but want to dig deeper into the more impressive stuff https://smile.amazon.com/dp/1491946008/ref=cm_sw_em_r_mt_dp_Q854MFBRT2YXG7ZCYT3B is my favorite resource.

Honestly, all contributions are extremely welcome, even if just catching speeling mistakes or the like.  I have a list of what I want to do overall https://github.com/cdgriffith/FastFlix/projects/1 , thought I think probably the best "foot in the water" thing would be some basic testing https://github.com/cdgriffith/FastFlix/issues/159 (it's not a hard of thing as others, just something I never seem to have time for) 

And lets keep the ticket open until I at least fix the requirements file, and I will close after the release.

**Comment by sclauss** [comment]
Thanks for all the information and your patience. I will keep the issue open.
And I see what you did there with the spelling... ;)

**Comment by adworacz** [comment]
I started seeing this issue today when I upgraded from 3.4.3 (which I had installed via `pipx`) to 4.2.3 (which I installed via direct download from the Github releases page, since the `pipx` version is massively out of date now).

```
2021-06-09 09:42:26 manjaro-desktop fastflix-core[216373] INFO Starting FastFlix 4.2.3
2021-06-09 09:42:26 manjaro-desktop fastflix-core[216373] DEBUG Conversion worker shutting down
```

This is on a Manjaro desktop, fully `pacman -Syu`'d as of a few seconds ago.

**Comment by cdgriffith** [comment]
Forgot to close when root issue of not version pinning was fixed, cleanup up now
