### ISSUE TITLE
[REQ] Versatile Video Coding (aka x266) support

### ISSUE THREAD

**Issue by forart** [cdgriffith/FastFlix#233]
Finally the 1.0.0 version has been (recently) released:

https://github.com/fraunhoferhhi/vvenc/releases/

Dunno if it'll be included in FFMPEG, btw it could be interesting to have a cool gui (like FF) for it.

Hope that inspires.

**Comment by cdgriffith** [comment]
Just as an update on this, won't be able to add until they have integration with FFmpeg or their own CLI tool that takes common video formats (current tool only takes raw frames)

**Comment by OnyxStreaming** [comment]
UPDATE: 
FFmpeg Now doing patchwork for VVC H.266 
all Updates on patchwork can be found [Here](https://patchwork.ffmpeg.org/project/ffmpeg/list/?series=3487)

**Comment by forart** [comment]
Just found this interesting git by @MartinEesmaa that *may* help:

https://github.com/MartinEesmaa/VVCEasy

**Comment by MartinEesmaa** [comment]
@forart, thanks for interesting to my repository :).

To all participants:
VVC should be ready stream compatability in 2024, but MX Player (tv streamer) and Spin Digital are closed source and sells vvc decoder realtime for customers requiring demo or/and license.
While @cdgriffith is taking a bit time to add VVC support on FastFlix, you can play VVC file on VLC Media Player (only Windows), see my repository:
https://github.com/MartinEesmaa/VVCEasy/tree/master/INSTALLVLCPLUGIN

If you have any difficults/questions, you can reply me.

Regards,
- Martin Eesmaa

**Comment by cdgriffith** [comment]
I haven't seen any news myself of VVC being added to most FFmpeg instances, at least the VVCEasy @forart lniked does comes with a FFmpeg compiled version I could use to add initial support. Thank you for those links! 

Adding to 5.2.0, beta with that feature now https://github.com/cdgriffith/FastFlix/releases/tag/5.2.0b3

I was able to complete a test encode, but couldn't play the video (and running their own `ffprobe` gave a segfault) so not 100% sure it's all working well, but trying to get it in here so it's ready when it does become more streamlined!

**Comment by forart** [comment]
Well, 1st of all thanks for the add.

Anyway @FranceBB recently clarified the situation by posting this slide @Doom9:
![](https://i.imgur.com/HMCUo0A.png)

More infos: https://forum.doom9.org/showthread.php?p=1982204#post1982204

Last but not least, hope @ultravideo's [uvg266](https://github.com/ultravideo/uvg266) will join the FastFlix party !

**Comment by FranceBB** [comment]
Well, as far as the patch for FFMpeg is concerned with the Fraunhofer stuff, it was about VVDec, not VVEnc, in other words their decoder, not their encoder. Unfortunately, although the Fraunhofer guys did a lot of work to integrate it, the FFMpeg community refused the pull request (twice). They're now attempting to get it merge for the third time...

As far as encoding is concerned, however, that will almost definitely be x266 from Multicoreware, which isn't ready to be integrated anywhere yet. Initially the roadmap was Q2 2023, but we'll see how things are gonna go. I mean, v1.0 was ready for early February while the original schedule was after Christmas so late December 2022, early January 2023, so I wouldn't be surprised to see it slip a bit after Q2 2023, but still...
Anyway, it's been a while since 2021 and a lot has been done in the meantime, so hopefully by no later than summer 2023 we should have something to play with in terms of x266 and then it's just gonna be a matter of the FFMpeg guys not opposing libx266.

Oh, speaking of a decoder, I think that VVDec from Fraunhofer will unfortunately not be integrated in the end in terms of FFMpeg as they'll end up developing one inside libavcodec themselves (the FFMpeg community, that is) so that they don't have to rely on third party for decoders. Unfortunately this will take time, but you can check the progress here: https://github.com/ffvvc/FFmpeg

**Comment by plhvlogs** [comment]
> I haven't seen any news myself of VVC being added to most FFmpeg instances, at least the VVCEasy @forart lniked does comes with a FFmpeg compiled version I could use to add initial support. Thank you for those links!
> 
> Adding to 5.2.0, beta with that feature now https://github.com/cdgriffith/FastFlix/releases/tag/5.2.0b3
> 
> I was able to complete a test encode, but couldn't play the video (and running their own `ffprobe` gave a segfault) so not 100% sure it's all working well, but trying to get it in here so it's ready when it does become more streamlined!

Hi, how can i enable v266 for this beta ver ?

**Comment by cdgriffith** [comment]
@plhvlogs you will need to download or compile a ffmpeg build that has the library in it, and link it in FastFlix. 

For example could download the one they shown above from https://github.com/MartinEesmaa/VVCEasy/blob/master/FFMPEGVVC.md#ffmpeg-downloads-xhe-aac--vvc-endecoder-plugin-compiled-by-martin-eesmaa 

Extra those files to a directory of your choice.

And then go into FastFlix, top left click File > Settings then edit `ffmpeg` and `ffprobe` paths to point to those versions, and restart FastFlix

**Comment by cdgriffith** [comment]
Added in [5.2.0](https://github.com/cdgriffith/FastFlix/releases/tag/5.2.0)!

**Comment by MartinEesmaa** [comment]
Thank you for adding VVC support, @cdgriffith!
- Martin Eesmaa
