### ISSUE TITLE
Any Plans to support MacOS

### ISSUE THREAD

**Issue by yehia2amer** [cdgriffith/FastFlix#27]
I Just want to know if this is going to support macOS since it is written in Python so I thought it should be feasible !

**Comment by cdgriffith** [comment]
The basis of the program could pretty easily handle linux / mac I think, the issue is SVT-AV1 (as of time of coding) only had windows builds being produced. However the meat of the program uses ffmpeg, so as long as not looking for SVT-AV1 specifically I could look into do that (or would accept PRs for). 

This was really just me building myself a tool to make HQ gifs easily / experiment with AV1, so I haven't been keeping up with it as you _may_ have noticed. 

Hope you are doing well in these interesting times!

**Comment by cdgriffith** [comment]
Well, surprising myself, I went ahead and made some major updates to this, including possible Mac usage. I say possible because I do not have OSX machine, and honestly haven't gotten the chance to even try it out on a linux VM yet.  But if you're adventurous feel free to try it out with the instructions at the release section https://github.com/cdgriffith/FastFlix#releases

**Comment by yehia2amer** [comment]
That's Great, I will try it and get back to you.
But how to run the app. is it just `python ./gui.py` ?

**Comment by cdgriffith** [comment]
```
git clone https://github.com/cdgriffith/FastFlix.git
cd FastFlix
python3 -m venv venv
. venv/bin/activate
pip install -r requirements.txt
python -m flix
```

**Comment by cdgriffith** [comment]
With 2.3.0 there is now an official pypi release, with an easier install https://github.com/cdgriffith/FastFlix#macos-and-linux
