### ISSUE TITLE
how to achieve Running from source code？

### ISSUE THREAD

**Issue by lgx419** [cdgriffith/FastFlix#288]
Hello, @cdgriffith ，I have a question for you.How can I add the video in the source code and set the parameter conversion format? Can the parameters be set directly in the program? If not, how can it be implemented in the source code? Thank you so much!

**Comment by cdgriffith** [comment]
Hi @lgx419, going to take a step further back and ask what is your end goal? 

FastFlix is a GUI wrapper around FFmpeg, are you looking at just how you can manually run FFmpeg commands? Or hoping to get a way to simply automate the creation of them with Python? 

If the latter, would not be ideal to use FastFlix, as it's design is primarily to support the GUI. For example, each encoder has it's own panel and command builder code, here is x265s command builder file https://github.com/cdgriffith/FastFlix/blob/master/fastflix/encoders/hevc_x265/command_builder.py and that is just for the video parameters. There are other ones for subs and audio, that don't make sense to run from the code directly.

**Comment by lgx419** [comment]
Thank you very much for your reply! My goal: FastFlix can input files and set parameters through the GUI interface. I want to input video files and set parameters through the source code, and get the output results, but I am new to programming, and I don't know much, so I don't know how to proceed, so I ask You, how can I achieve my goal? The function of each package of the source program and which file is the main program, is it convenient to talk about it?



---Original---
From: "Chris ***@***.***&gt;
Date: Thu, Jan 20, 2022 22:45 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [cdgriffith/FastFlix] how to achieve Running from source code？ (Issue #288)




 
Hi @lgx419, going to take a step further back and ask what is your end goal?
 
FastFlix is a GUI wrapper around FFmpeg, are you looking at just how you can manually run FFmpeg commands? Or hoping to get a way to simply automate the creation of them with Python?
 
If the latter, would not be ideal to use FastFlix, as it's design is primarily to support the GUI. For example, each encoder has it's own panel and command builder code, here is x265s command builder file https://github.com/cdgriffith/FastFlix/blob/master/fastflix/encoders/hevc_x265/command_builder.py and that is just for the video parameters. There are other ones for subs and audio, that don't make sense to run from the code directly.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cdgriffith** [comment]
The functional programming and GUI code are extremely tightly coupled so it is not reasonably possible to do that sadly. 

For example when you "add the video" in the source code, a lot of operations have to trigger to setup the other elements of the GUI so that the program command will be built https://github.com/cdgriffith/FastFlix/blob/master/fastflix/widgets/main.py#L954

That will trigger [page_update](https://github.com/cdgriffith/FastFlix/blob/26c53d10fb9b2d9e73382a78a7276bb2389bd5c5/fastflix/widgets/main.py#L1681), which triggers [build_commands](https://github.com/cdgriffith/FastFlix/blob/26c53d10fb9b2d9e73382a78a7276bb2389bd5c5/fastflix/widgets/main.py#L1627) which then will use whichever encoder is currently loaded to [build the final command(s)](https://github.com/cdgriffith/FastFlix/blob/26c53d10fb9b2d9e73382a78a7276bb2389bd5c5/fastflix/widgets/main.py#L1641). 

Now if you wanted to basically rip away the GUI, I have been working hard to set all parameters up as pydantic models. So while it would be a bit of work, could pull the [builder code](https://github.com/cdgriffith/FastFlix/blob/master/fastflix/encoders/vceencc_avc/command_builder.py) from the encoder you want to use and grab the [models](https://github.com/cdgriffith/FastFlix/tree/master/fastflix/models) and manually fill everything in. Would make a it a lot easier to fill in video info by modifying [parse](https://github.com/cdgriffith/FastFlix/blob/master/fastflix/flix.py#L172) from the flix file as well. 

That is obviously something I would not attempt as a beginner programmer, just the best answer I can provide.

**Comment by lgx419** [comment]
Thank you very much for your reply, it is instructive to me, I wish you a happy life!
