### ISSUE TITLE
Can I have a way to disable debug window?

### ISSUE THREAD

**Issue by smtad** [cdgriffith/FastFlix#291]
The additional debug window is too annoying, it's useless for normal user.
I hope you'll add a config to disable it.

**Comment by cdgriffith** [comment]
Shouldn't be showing unless you have an environment variable set to DEVMODE=1

**Comment by smtad** [comment]
I don't have an environment variable called DEVMODE. But even I set DEVMODE=0, it still show debug window.

**Comment by cdgriffith** [comment]
OH. Sorry, there is actually a debug mode that adds another pane inside the FastFlix app is what I thought you meant at first. 

The console window that opens on launch is needed as it separates the encoding process from the GUI itself. That way if the GUI fails for some reason, the encoding does not automatically die. (It also historically exists because the program that packages the python code into an executable for different platoforms, Pyinstaller, had issues when disabling it.) 

So sadly for time being it does need to exist.
