### ISSUE TITLE
MediaInfo not showing correct HDR10+ tag

### ISSUE THREAD

**Issue by rivertim** [cdgriffith/FastFlix#299]
HDR10+ file exported from DaVinci Resolve 17.4, exported with sidecar json HDR10+ metadata file

Using FastFlix to mux files to final .mkv exports, but notice that MediaInfo shows HDR Format tag as:

`SMPTE ST 2086, HDR10 compatible`

It should show 

`SMPTE ST 2094 App 4, Version 1, HDR10+ Profile B compatible`

Compatible TV needs this tag present to trigger full HDR10+ I believe. Any thoughts?

Many thanks for great tool!

**Comment by rivertim** [comment]
PS When exporting sidecar json file from Resolve Timeline, ensure correct file type "Profile B" is selected. This will inject the "BezierCurveData" info to make the json file HDR10+ correct. However, the problem noted above still stands, and the HDR Format tag is not currently written as HDR10+, and is not therefore triggering the TV into anything other than standard HDR10 mode.

**Comment by cdgriffith** [comment]
Sorry you're having issues! This might be because your FFmpeg bundled x265 doesn't have HDR10+, or x265 simply doesn't recognize Resolve's format. We can try to narrow that down.

On your encodings, in the logs at the start of the encode there will be a section of output from the `x265` encoder showing the options it has set. (Can either view past logs via Help > Open Log Directory or try a new encode) 

Make sure the line `x265 [info]: tools: dhdr10-info` exists!

```
...
x265 [info]: Keyframe min / max / scenecut / bias  : 25 / 250 / 40 / 5.00
x265 [info]: Lookahead / bframes / badapt        : 15 / 4 / 2
x265 [info]: b-pyramid / weightp / weightb       : 1 / 1 / 0
x265 [info]: References / ref-limit  cu / depth  : 2 / on / on
x265 [info]: AQ: mode / str / qg-size / cu-tree  : 2 / 1.0 / 32 / 1
x265 [info]: Rate Control / qCompress            : CRF-18.0 / 0.60
x265 [info]: tools: rd=2 psy-rd=2.00 early-skip rskip mode=1 signhide tmvp
x265 [info]: tools: fast-intra strong-intra-smoothing lslices=6 deblock sao
x265 [info]: tools: dhdr10-info
```

There is no easy way to tell if the bundled `x265` has it or not without simply trying it. If you don't see that, please try with the test media file https://github.com/cdgriffith/FastFlix/tree/master/tests/media  (will need the hdr10plus tool downloaded and linked via settings). Add it to FastFlix and click `Extract HDR10+` down beside the `HDR10+ Metadata` line and do a quick encode and see if that one works as expected.  Shows as `SMPTE ST 2094 App 4, Version 1, HDR10+ Profile B compatible` for me.

For windows and linux the recommended `FFmpeg` builds are listed in the wiki https://github.com/cdgriffith/FastFlix/wiki#ffmpeg

**Comment by rivertim** [comment]
Thanks! I have this line:

`fastflix-core[5264] INFO x265 [warning]: --dhdr10-info disabled. Enable HDR10_PLUS in cmake.`
:(
I have no Extract HDR10+ Button (beside the import HDR10+ metadata?) on my FastFlix GUI!

If I check your test file in MediaInfo it shows:

`HDR format : SMPTE ST 2094 App 4, Version 1, HDR10 compatible`
not HDR10+

**Comment by cdgriffith** [comment]
Yeah if you have that error `--dhdr10-info disabled` you'll need to grab a better `FFmpeg` package. What OS are you on? 

For Windows I recommend https://github.com/BtbN/FFmpeg-Builds/releases

For Linux/Mac will need to build yourself, I like https://github.com/markus-perl/ffmpeg-build-script#quick-install-and-run-macos-linux  (make sure to grab the "With GPL and non-free codes" version)

**Comment by rivertim** [comment]
Update: FFmpeg installed as per your script ok. 
Exporting HDR10+ .mkv with metadata now shows correctly in MediaInfo:

`SMPTE ST 2086, HDR10 compatible / SMPTE ST 2094 App 4, Version 1, HDR10+ Profile B compatible`

Can I chose to export .mp4 instead of .mkv?

Thanks for your help!

**Comment by cdgriffith** [comment]
Wow, sorry I missed this thought I replied earlier. 

Yes, you can change the `.mkv` to to `.mp4` in the "Output" path on the top left of FastFlix. It will give a warning message when you hit "Convert" about the container type, but you can ignore it. (Mostly matters if using incompatible audio / subtitles will error out.)

**Comment by cdgriffith** [comment]
Closing this for now as main issue addressed, but if you have more questions / comments please feel free to keep replying or open new issues as needed!
