### ISSUE TITLE
Advanced - VBV doesn't do anything (AVC x264)

### ISSUE THREAD

**Issue by phuckstepp** [cdgriffith/FastFlix#302]
I just converted a video file twice to test out the VBV options

1. VBV enabled and set to max rate 6000kbps and Bufsize of 3000
2. VBV disabled

all other options were set exactly the same for the AVC (x264) encoding. The Raw Commands panel showed no change between enabling and disabling the VBV option and both output files came out identical at 1.75Gb.

Is the VBV option actually working or is it only available with certain encoding settings?

Note: I installed FastFlix for the first time yesterday and so is the latest version and has the latest FFMPEG installed.

**Comment by cdgriffith** [comment]
I just tried myself, had an issue myself, and I think I see what the problem is. 

Make sure that Bufsize field actually has a value in it (aka go type "3000" in by hand.) 

With the updated theme the placeholder text is the same color (or close enough) as the "real" value color. So it looks like there is a value in there, but if either field is empty it is not applied. 

Labeling this as BUG as the theme needs some clarity there or some way of alerting the user that it's not being applied.

**Comment by cdgriffith** [comment]
Making it much more clear how to use VBV in the advanced panel in 4.7.0 https://github.com/cdgriffith/FastFlix/releases/tag/4.7.0
