### ISSUE TITLE
GUI oversized with 4k high DPI monitor

### ISSUE THREAD

**Issue by wynterca** [cdgriffith/FastFlix#320]
I am on Windows 10 and have a 4k monitor set with display scaling at 150%.  The GUI is now 50% oversized (takes more than half the screen when shrunk to min window size where it used to take about a 1/4 of the overall screen).  If I go into the properties for fastflix.exe and change the compatability tab settings under "High DPI Settings" for "High DPI Scaling" to overide with "system" or "system (enhanced)" the window size returns to normal as it used to be in versions 4.7.x.

**Comment by Wontell** [comment]
It will be nice [if the dev has time for this] to add a scaling option like say MSI Afterburner tool, which has option in settings to scale the gui from 75% to 200%

P.S. Im also on 4K, but months ago got tired of constant random software issues with scaling, I used 125% first, then 115% and now i switched to 0% scaling.
It took some time to get used to, maybe because im using 55inch OLED as monitor its easier since everything is bigger by default, but now i have no scaling issue with any software.

**Comment by cdgriffith** [comment]
There is a "hidden" environment variable config for this right now that needs to be made an option at some point. `FF_DPI_OFF`

For example if you have it installed in program files, can open a command prompt and enter:

```
set FF_DPI_OFF=1
"C:\Program Files\FastFlix\FastFlix.exe"
```

With 4.8.0 I switched back to PySide2 to support older windows versions (instead of PySide6) and it isn't as friendly with scaling, so not sure how best to address it to be honest.

**Comment by cdgriffith** [comment]
With the latest https://github.com/cdgriffith/FastFlix/releases/tag/5.1.0 this might be better?

**Comment by cdgriffith** [comment]
Added in [5.2.0](https://github.com/cdgriffith/FastFlix/releases/tag/5.2.0)! Go to setting > UI Scaling > Disable
