### ISSUE TITLE
My bash script to help users with batch processing

### ISSUE THREAD

**Issue by gab-luz** [cdgriffith/FastFlix#369]
Hey guys. I wanted to share my script to help users with batch processing because this is something that is not available on FastFlix yet.
My script below basically grabs any mp4 it finds inside the current folders and inside all subfolders and converts them to an H265 MKV files CRF 28, Opus audio with 64kbps.
You just have to modify the lines if you want to make it better.

```
#!/usr/bin/env bash
find ./ -name '*.mp4' -exec bash -c 'nvencc -i "$0" --video-metadata clear --metadata clear \
--chapter-copy -c hevc --cqp 28 --bref-mode disabled --preset quality \
--tier high --no-aq --level auto --colormatrix bt709 --transfer bt709 \
--colorprim bt709 --output-depth 10 --multipass 2pass-full --mv-precision Auto \
--chromaloc auto --colorrange auto --avsync cfr   --audio-codec libopus --audio-bitrate 64 \
--audio-metadata clear   -m default_mlsode:infer_no_subs -o "${0/mp4/mkv}"' {} \;
notify-send "FastFlix Batch" "Conversion done."
```

**Comment by namus80** [comment]
Hello, Sorry newbie here. Is there any way to adapt this script for windows.  Batch processing is something I have waiting for and I would be grateful if you let me know how to use this on windows or suggest the correct changes for windows. Thank you.

**Comment by astalavistababe** [comment]
Hi, this is my batch scripts for windows,

if not exist "mkv_out" (mkdir "mkv_out")
for %%a in ("*") do C:\NVEncC_7.08_x64\NVEncC64.exe -i "%%a" --video-streamid 1 --video-metadata clear --metadata clear --chapter-copy -c hevc --vbr 1500 --vbr-quality 32 --qp-init 30:30:30 --qp-min 32:32:32 --qp-max 34:34:34 --bframes 6 --ref 6 --bref-mode middle --preset P7 --tier high --lookahead 32 --aq --aq-strength 15 --level auto --colormatrix auto --transfer auto --colorprim auto --output-depth 8 --multipass 2pass-full --mv-precision Q-pel --chromaloc auto --colorrange auto --audio-codec --output "mkv_out\%%~na.mkv"
pause

download rigaya NVEncC from 
https://github.com/rigaya/NVEnc/releases
extract wherever you want
then replace this path "C:\NVEncC_7.08_x64\NVEncC64.exe" in the script with your desired path.

for parameter and options docs refer to this link
https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md

Credits to rigaya
https://github.com/rigaya

**Comment by dvize** [comment]
Here is my version using av1 NVEncC support for hardware nvenc.

`
if not exist "mkv_out" (mkdir "mkv_out")
for %%a in ("*") do C:\nvenc\NVEncC64.exe -i "%%a" --video-streamid 1 --video-metadata clear --metadata clear --chapter-copy -c av1 --vbr 5000 --bref-mode disabled --preset quality --tier high --aq-temporal --aq-strength 0 --level auto --colormatrix bt709 --transfer bt709 --colorprim bt709 --output-depth 8 --multipass 2pass-full --mv-precision Auto --chromaloc auto --colorrange auto --avsync cfr --psnr --ssim     -m default_mode:infer_no_subs --output "mkv_out\%%~na.mkv"
pause
`

Note, you should not run this as admin otherwise it will not run in the directory you place it in.
You can also tweak these settings by looking at the raw output of fastflix.  
I fixed the output from astalavistababe and made sure it actually output to the mkv_out folder.

**Comment by namus80** [comment]
Thank you astalavistababe and dvize for the code. Much appreciated

**Comment by cdgriffith** [comment]
Batch processing support added in https://github.com/cdgriffith/FastFlix/releases/tag/5.2.0 !
