### ISSUE TITLE
Using x265 encoder on intel 13900 doesn't use P-Core for encoding

### ISSUE THREAD

**Issue by iccfish** [cdgriffith/FastFlix#415]
HI, I'm running fastfix on Windows 11 @ Intel 13900K. I notieced that x265 encoder runs on all E-Cores but none P-Core.

I wonder if this is by design or I miss something?

**Comment by cdgriffith** [comment]
This is due to older versions of FFmpeg not understanding the newer chips design. I would download the latest available ffmpeg https://github.com/BtbN/FFmpeg-Builds/releases/tag/latest  if you're unsure of which I would chose 
ffmpeg-master-latest-win64-gpl.zip  

If that doesn't work other thing to make sure of: 
1. Windows is fully updated
2. Latest intel firmware installed for the CPU
3. Latest BIOS for the motherboard is installed

**Comment by iccfish** [comment]
My ffmpeg version was 'ffmpeg version N-109433-g48d5aecfc4-20221219', it shouldn't too old ...maybe it caused by compiler version .... it was built with gcc.

I'll try other ffmpeg builds later..

Other three points all checked and all satisfied.

**Comment by cdgriffith** [comment]
Changing this over to a discussion https://github.com/cdgriffith/FastFlix/discussions/444 as an FYI to merge multiple issues and hopefully make it easier for people to comment on it.
