### ISSUE TITLE
[REQ] FFMPEG's video capture (as source) support

### ISSUE THREAD

**Issue by MarcoRavich** [cdgriffith/FastFlix#418]
As always thank you for your valuable work as well as your careful listening to users' requests.

Even if it probably don't falls within the project scope, it would be extremely interesting (and could make FF almost unique) to implement FFMPEG video capture as input.

We've got inspired by @Jessecar96's git on [How to capture, deinterlace, and encode analog video](https://github.com/Jessecar96/analog-capture#how-to-capture-deinterlace-and-encode-analog-video) which proposes an [interesting method](https://github.com/Jessecar96/analog-capture#method-1) on how to set FFMPEG for video capture through dedicated hardware.

The most interesting (and recently made) resource is probably @StefanoLusardi's [Video Capture wrapper for FFMPEG with Software/Hardware decoding](https://github.com/StefanoLusardi/video_capture) and there's also [vcr](https://github.com/BurntSushi/vcr) by @BurntSushi or - a bit dated - git by @joncampbell123 who has implemented _"video capture, live feed display, and recording to an AVI file when recording activated"_ through FFMPEG in his [Video capture and archiving utility for Linux](https://github.com/joncampbell123/video-capture-v1-public#readme).

If it helps to let you implement it easier, here are some simple FFMPEG capture scripts to get inspiration from:
- [A collection of scripts to capture video with ffmpeg-python](https://github.com/zfleeman/ffmpeg-python-scripts#ffmpeg-python-scripts) by @zfleeman 
- [FFMPEG scripts](https://github.com/modeler/vhs-capture) by @modeler
- [FFMPEG-Capture](https://github.com/pcntv/FFMPEG-Capture) by @pcntv

Last but not least @egemengulpinar's [capture-device-list](https://github.com/egemengulpinar/capture-device-list#capture-device-list) on Windows or @ericwooley's [ffmpeg-devices](https://github.com/ericwooley/ffmpeg-devices) on Mac may also help.

Hope that inspires !

**Comment by forart** [comment]
OK here's the 1st quick test (played by Panasonic NV-HD630 on Blackmagic Intensity Pro).

commandline:
`ffplay -pixel_format uyvy422 -framerate 25 -f dshow -i video="Decklink Video Capture":audio="Decklink Audio Capture" -aspect 4:3 -vf "yadif=1"`

screenshot:
![ffplay](https://user-images.githubusercontent.com/171307/221614264-3b441c24-899f-4c06-9ae2-ad64a89bcbe7.png)

**Comment by forart** [comment]
@zfleeman thanks for your scripts and hints !

There are a bunch of video capture parameters to consider in order to achieve good results in analog video digitization.

Many are nicely explained by @ViRb3 in his [sdconv script page](https://github.com/ViRb3/sdconv):
- Deinterlacing
- [PAR](https://github.com/ViRb3/sdconv#anamorphic-dimensions) 
- [chromaticity](https://github.com/ViRb3/sdconv#chromaticities)
- lossless encode
- etc.

We would love to put all these efforts into an a single ffmpeg commandline to let cool devs like @cdgriffith easily implements is in their GUIs.

About `rtbufsize` we do see different approaches: for example, in @pcntv [record.bat](https://github.com/pcntv/FFMPEG-Capture/blob/master/record.bat) is set to 1500M...
`-rtbufsize 1500M -f dshow -pixel_format  uyvy422 -framerate 29.97 -i video="Blackmagic WDM Capture":audio="Blackmagic WDM Capture"`

...this means there's not a standard value to set.

Hope we could collaborate to reac the goal.

**Comment by forart** [comment]
...still investigating...

According to many, `yadif=0:-1:0` should give better results.

**Comment by forart** [comment]
After some research, here's a new test: 

![ffplay2](https://user-images.githubusercontent.com/171307/221958978-4b015bb0-f3e6-48a5-a301-d8b85f3a28d4.png)

commandline used:

`ffplay -rtbufsize 1G -pixel_format uyvy422 -framerate 25 -f dshow -i video="Decklink Video Capture":audio="Decklink Audio Capture" -aspect 4:3 -vf "bwdif=mode=send_field:parity=auto:deint=all"`

(note: changed VCR in order to preserve the main one, test done on Samsung DVD-V6700 combo)

**Comment by forart** [comment]
...still testing...

`ffplay -rtbufsize 1G -pixel_format uyvy422 -framerate 25 -f dshow -i video="Decklink Video Capture":audio="Decklink Audio Capture" -aspect 4:3 -vf "scale=in_range=full:out_range=full,lut='y=(va l-16)*1.067',bwdif=mode=send_field:parity=auto:deint=all,crop=702:564:6:2"`

Inspired by [this post @ videohelp](https://forum.videohelp.com/threads/405794-VHS-PAL-cutting-and-upscaling/page2#post2659544).

**Comment by forart** [comment]
Found an interesting Python code by @miguelfazenda called [VCR](https://github.com/miguelfazenda/VCR):
https://github.com/miguelfazenda/VCR/blob/master/recorder.py

**Comment by forart** [comment]
(still investigating)
...there are many interesting discussions about _sws_flags_ usage to preserve video quality, but we honestly don't know if these parameters can also be useful in the acquisition phase:
>Always add +accurate_rnd+full_chroma_int to sws_flags (by -sws_flags +accurate_rnd+full_chroma_int or sws_flags=+accurate_rnd+full_chroma_int in filtergraphs, or both), unless speed is prefered over quality.
Source: https://trac.ffmpeg.org/ticket/1582#comment:15

**Comment by forart** [comment]
Very interesting finds to consider:

https://digitensions.home.blog/2019/03/18/moving-video-tape-capture-to-an-open-source-workflow/

https://blogs.library.duke.edu/bitstreams/2021/03/12/ffv1-the-gains-of-lossless/

**Comment by forart** [comment]
**[FUN] chatGPT "opinion"**

Here's an FFMPEG command line that you can use on Windows to acquire an audio/video stream from a capture card using a lossless codec:

`ffmpeg -f dshow -i video="Your Capture Card Name" -f dshow -i audio="Your Audio Device Name" -c:v utvideo -c:a pcm_s16le -pix_fmt yuv420p -preset ultrafast output.avi`

This command assumes that you have installed FFMPEG on your Windows system and that you know the names of your capture card and audio device.

Replace "Your Capture Card Name" and "Your Audio Device Name" with the actual names of your capture card and audio device. You can find the names of your devices by running the command ffmpeg -list_devices true -f dshow -i dummy.

The command uses the dshow input format to capture video and audio from the specified devices. It encodes the video using the lossless utvideo codec and the audio using the uncompressed pcm_s16le codec. The output file format is AVI, and the output video is in yuv420p pixel format. The ultrafast preset is used to encode the video quickly, but you can choose a different preset if you want to trade off encoding speed for file size.

The output is saved to a file named "output.avi" in the current directory. You can change the filename and path to save the output file to a different location.

**Comment by cdgriffith** [comment]
These are fun ideas, but way outside anything I was thinking when making this program and is very ill suited for from a coding perspective. It's all open source, so anyone else can have at it if they wish, but this is not something I could see being added myself. 

Other discussion: https://github.com/cdgriffith/FastFlix/issues/342
