### ISSUE TITLE
Release 5.2.1: Missing Ubuntu 20 (Debian 11) package?

### ISSUE THREAD

**Issue by rharmonson** [cdgriffith/FastFlix#431]
Release 5.2.1 doesn't have a Ubuntu 20 (Debian 11) package?

Hopefully, this is an oversight. I use Debian 11.

**Comment by rharmonson** [comment]
On reflection, it wouldn' t matter. With you pushing the python version to 3.11, the package wouldn't work and   compiling from source will fail on Debian Stable.

Ugh.

You must have a reason for pushing to python11. I will hunt for a solution but looks like I will be staying with FastFlix 5.1.0.

**Comment by cdgriffith** [comment]
Hi @rharmonson, thanks for pointing that out! I was actually hopeful to push everything for *nix and macOS into homebrew for 5.2.0, but ran out of time. As part of that I removed older versions builds because those would have been done just through homebrew (long term goal still)

Adding back in the Ubuntu 20 build for 5.2.2!

**Comment by rharmonson** [comment]
Understood and thank you for the update.

I recognize Debian stable may be bit of a challenge but it still going to be supported for 12 to 18 months. They have not given a definite EoL, yet. Well, not that I can find.

You heard me say this before but it needs to be said, again, FastFlix is amazing. No, I won't install Ubuntu to use it, but I will jump through hoops within reason to use it on Debian Stable :).

**Comment by cdgriffith** [comment]
Thank you! The goal is honestly to support more platforms more easily. Right now build on ubuntu (because that's what the github runners has), means it still can be funky on Debian or other linux versions (And don't even get me started with macs!). Hence why trying to move something like homebrew.  

No perfect solution, and don't have resources or helpers to build distro specific releases, so just trying for simplest broadest methods. 

Ubuntu 20 builds are back in 5.2.2! https://github.com/cdgriffith/FastFlix/releases/tag/5.2.2  If they aren't running let me know, I don't have a Debian / older ubunutu VM currently running to actually test on.

**Comment by rharmonson** [comment]
@cdgriffith, installed 5.2.3 and launches without errors. I'll do several encodes this weekend to test and open an issue if run into problems.

Thank you.
