### ISSUE TITLE
Fastflix is detected as Trojan/Virus/Malware

### ISSUE THREAD

**Issue by MrWGT** [cdgriffith/FastFlix#527]
**FastFlix Version:**
5.5.7 downloaded from github releases

**Operating System:**
Win 11
**Describe the bug**

Win 11 detects Fastflix since today as

Trojan:Win32/Bearfoos.A!ml
[Detected by Microsoft Defender Antivirus](https://www.microsoft.com/en-us/windows/windows-defender?ocid=cx-wdsi-ency)

and is automatically removed.

**To Reproduce**
Steps to reproduce the behavior
Don't know? Latest Defender Update?

**Screenshots**

**Logs** (If applicable) In FastFlix you can go to Help > Open Log Directory and sort by latest to find the newest log file to add here.

Please make sure to remove any personal information or video names in the screenshots and logs!

**Comment by RayBB** [comment]
VirusTotal doesn't seem to detect this on the zip:
https://www.virustotal.com/gui/url/244111ae3eb22bbb5367cf2971e982d095f5b39a059abad53dc22640457c090b

But def detects it on the exe for several antivirus:
https://www.virustotal.com/gui/file/0e3df4b2a588fa2941d0f8e0a316e5257387e8adac1f1335c5572ac11f43028f

The latest installer does not have the issue:
https://www.virustotal.com/gui/url-analysis/u-9d8b73405f06dc956a18024aaafd97d9723edc72f43701967605dc62660ab69a-1696610155

The latest mac executable doesn't seem to have such an issue:
https://www.virustotal.com/gui/file-analysis/MTU5N2U0NjNmNTlkNjUwOWYwYmQ3MjY0NjE1ZDhmM2E6MTY5NjYxMDExNQ==

**Comment by cdgriffith** [comment]
Anytime there is a Pyinstaller update it will probably be re-flagged by some. As I use the same program to create the EXE as a lot of others, plenty of whom do so maliciously, the anti-viruses understandably err on the side of caution. 

Basically make sure the EXE has been digitally signed by me and should be safe https://github.com/cdgriffith/FastFlix/issues/274#issuecomment-959717295

**Comment by unggulzmalqp** [comment]
Just for your awareness, the installed exe also have this problem. 


![afbeelding](https://github.com/cdgriffith/FastFlix/assets/16437339/07bb6abd-0754-479b-a2cc-fba1fd39a02b)

**Comment by cdgriffith** [comment]
FastFlix executables are getting tripped as virus on some AVs such as bitwarden. If that happens to you, 

1. Double check the EXE is [digitally signed by me](https://github.com/cdgriffith/FastFlix/issues/274#issuecomment-959717295) (right click, properties, digital signatures. Should show "Chris Griffith").
2. Report it to your AV provider as a false positive.

This happens when the packager PyInstaller (the thing used to make the EXEs for windows) updates to newer versions. Due to everyone, including bad actors, using it to make EXEs, so new malware is found with similar code and they flag anything close.
