### ISSUE TITLE
HDR2SDR double tonemapping in Rigaya NVENC and QSV Encoders

### ISSUE THREAD

**Issue by Darksyderz** [cdgriffith/FastFlix#605]
Hello <3 huge lover of fastflix, found this after trying handbrake and found it much easier for most things. been having issues with HDR2SDR tonemapping though, specifically with the Rigaya set of encoders. i usually use reinhard TMPing due to its overall look. when using the rigaya encoders either compiled from source or precompiled. i seem to have a double tonemapping issue causing the end footage to be absolutely garbled. enclosed below are the commands it outputs that are problematic as well as screenshots showing the non default nvenc encoder, qsv encoder and the default nvenc option with HDR removal and reinhard tonemapping shown. any help would definitely be appreciated as Rs encoders do a faster job overall with more control.

> Content with personal information removed

**Comment by cdgriffith** [comment]
Hello @Darksyderz can you please use online example files such as https://github.com/cdgriffith/FastFlix/blob/master/tests/media/Beverly%20Hills%20Duck%20Pond%20-%20HDR10plus%20-%20Jessica%20Payne.mp4 to test with.  Or from https://4kmedia.org/

Making sure I understand, the issue is happening on in both Rigaya's encoders but not ffmpeg's built in nvenc one?

**Comment by cdgriffith** [comment]
Acutally found out where the error in code this is happening. Will fix, thanks for raising the issue!

**Comment by Darksyderz** [comment]
wow thank you for the super quick response <3 much love and appreciation for all the work you do my friend.
