### ISSUE TITLE
Malware in FastFlix_5.8.2_installer.exe on github

### ISSUE THREAD

**Issue by amaeru16** [cdgriffith/FastFlix#621]
**FastFlix Version:**

V5.8.1 trying to update to the new one

**Operating System:**

Windows11 x64

**Describe the bug**
I tried to update the software from the app itself, it downloaded from github https://[objects.githubusercontent.com](https://objects.githubusercontent.com/)/. When i ran it, my antivirus (avast) said it was infected by "FileRepMalware [Misc]"

**To Reproduce**
Updating from the app it'self the installer.exe

**Screenshots**

https://imgur.com/M3t5FJZ

**Comment by cdgriffith** [comment]
This is due to other bad actors also using the same packaging software that a lot of python programs use for windows. And the AVs being lazy and grouping everything that looks near the same together for faster processing. Aka the "signature" 

Please report it to them as a false positive. If they come back saying there is actually something wrong, of course please re-open! 

Duplicate of https://github.com/cdgriffith/FastFlix/issues/527

**Comment by amaeru16** [comment]
Perfect, thank you for your answer
