### ISSUE TITLE
Import Metadata from HDR10+ in GUI

### ISSUE THREAD

**Issue by SlashX** [cdgriffith/FastFlix#83]
Hello, I have a galaxy s10 and I want to use your application to compress my vide shots.
I use this to extract metadata from my video:
`ffmpeg.exe -i "20201017_145050.mp4" -c:v copy -vbsf hevc_mp4toannexb -f hevc - | hdr10plus_parser.exe -o metadata.json -`
Screenshot
![Quality](https://user-images.githubusercontent.com/29688/96339528-0930c380-109e-11eb-9cab-04bddecd6819.jpg)

And then 
When i try to add the --dhdr10-info = metadata.json option in the interface it tells me that Unrecognized option '-dhdr10-info = metadata.json'.

Screenshot
![Encoding Status](https://user-images.githubusercontent.com/29688/96339545-282f5580-109e-11eb-8fed-08e893d6c06d.jpg)

I have this command line
![Command List](https://user-images.githubusercontent.com/29688/96339552-31b8bd80-109e-11eb-9ba4-a2c62ef8714f.jpg)

Is there a way to import metadata file extracted from original HDR10+ video in GUI so that I can compress the video but keeping the video HDR10+?

**Comment by cdgriffith** [comment]
Short answer: Not currently possible. It's a desire to add, but probably won't work for most people out of the box  (due to default FFmpeg builds).

`--dhdr10-info` is the `x265` command line option, so it needs to be passed via the `-x265-params` when used with FFmpeg. (Aka at end of options add `:dhdr10-info=metadata.json` )

The problem is that the version of libx265 that is built with most copies of FFmpeg does not have HDR10+ support turned on. So it would require a custom compilation. It's also not something that I am aware is easy to programmatically test if it is available, nor does it error when it's missing, just as part of the output log will say something like "unknown option, ignoring". Which means if added to the GUI and don't somehow specifically catch that message then people might have false expectations. 

I have a brief bit of info how to do it with your own version of x265 here: https://codecalamity.com/encoding-uhd-4k-hdr10-videos-with-ffmpeg/#extracting-and-encoding-with-hdr10-metadata

**Comment by SlashX** [comment]
Thank you! Your GUI is really easy to use and helpful, it has all the options you need, simple, but complex.
In the future, if you cand add that, it will be the best.
I think, add a check box to open a browse file to import metadata when you select HDR10, it Wii be the best. If you don check, to encode with normal HDR10. I know how hard must be to make this.
Thank you again for the hard work you put.

**Comment by cdgriffith** [comment]
I was actually able to get the FFmpeg build group I use to [include HDR10+](https://github.com/BtbN/FFmpeg-Builds/pull/17) in FFmpeg Windows builds so we are one step closer to making this a reality!

**Comment by SlashX** [comment]
Those are good new,
Thank you for the hard work!

**Comment by cdgriffith** [comment]
This feature has been added in [3.4.0](https://github.com/cdgriffith/FastFlix/releases/tag/3.4.0)!

I only had a single video to test with, so it's still highly experimental as a warning.

**Comment by SlashX** [comment]
Thank your for this feature and the hardworking!
